# Generated by Django 4.1.7 on 2023-04-01 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='rating')),
                ('profile', models.TextField(blank=True, null=True, verbose_name='profile')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='skills')),
                ('profile_picture', models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='profile_pics')),
                ('verified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailsHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verf', models.UUIDField(blank=True, null=True, verbose_name='email_verf')),
                ('pass_verf', models.UUIDField(blank=True, null=True, verbose_name='pass_verf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
