# Generated by Django 4.1.7 on 2023-04-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_question_expert_alter_question_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
